package com.cj.ebike.entity;

// Generated 2012-12-4 14:02:03 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductDetailsByProperty generated by hbm2java
 */
@Entity
public class ProductDetailsByProperty implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private PropertyType propertyType;
	private Product product;
	private String propertyValueEn;
	private String propertyValueGm;
	private Date createDate;

	public ProductDetailsByProperty()
	{
	}

	public ProductDetailsByProperty(int id)
	{
		this.id = id;
	}

	public ProductDetailsByProperty(int id, PropertyType propertyType,
			Product product, String propertyValueEn,
			String propertyValueGm, Date createDate)
	{
		this.id = id;
		this.propertyType = propertyType;
		this.product = product;
		this.propertyValueEn = propertyValueEn;
		this.propertyValueGm = propertyValueGm;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propertyId")
	public PropertyType getPropertyType()
	{
		return this.propertyType;
	}

	public void setPropertyType(PropertyType propertyType)
	{
		this.propertyType = propertyType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct()
	{
		return this.product;
	}

	public void setProduct(Product product)
	{
		this.product = product;
	}

	@Column(name = "propertyValueEn", length = 100)
	public String getPropertyValueEn()
	{
		return this.propertyValueEn;
	}

	public void setPropertyValueEn(String propertyValueEn)
	{
		this.propertyValueEn = propertyValueEn;
	}

	@Column(name = "propertyValueGm")
	public String getPropertyValueGm()
	{
		return this.propertyValueGm;
	}

	public void setPropertyValueGm(String propertyValueGm)
	{
		this.propertyValueGm = propertyValueGm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 23)
	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}

}
