package com.cj.ebike.entity;

// Generated 2012-12-4 14:02:03 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductDetailsByImage generated by hbm2java
 */
@Entity
public class ProductDetailsByImage implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int id;
	private Product product;
	private String imageUrl;
	private String descEn;
	private String descGm;
	private Double startX;
	private Double startY;
	private Date createDate;
	private String textEn;
	private String textGm;

	public ProductDetailsByImage()
	{
	}

	public ProductDetailsByImage(int id)
	{
		this.id = id;
	}

	public ProductDetailsByImage(int id, Product product, String imageUrl,
			String descEn, String descGm, Double startX, Double startY,
			Date createDate, String textEn, String textGm)
	{
		this.id = id;
		this.product = product;
		this.imageUrl = imageUrl;
		this.descEn = descEn;
		this.descGm = descGm;
		this.startX = startX;
		this.startY = startY;
		this.createDate = createDate;
		this.textEn = textEn;
		this.textGm = textGm;
	}

	@Id
	@GeneratedValue
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct()
	{
		return this.product;
	}

	public void setProduct(Product product)
	{
		this.product = product;
	}

	public String getImageUrl()
	{
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl)
	{
		this.imageUrl = imageUrl;
	}

	public String getDescEn()
	{
		return this.descEn;
	}

	public void setDescEn(String descEn)
	{
		this.descEn = descEn;
	}

	public String getDescGm()
	{
		return this.descGm;
	}

	public void setDescGm(String descGm)
	{
		this.descGm = descGm;
	}
	public Double getStartX()
	{
		return this.startX;
	}

	public void setStartX(Double startX)
	{
		this.startX = startX;
	}

	public Double getStartY()
	{
		return this.startY;
	}

	public void setStartY(Double startY)
	{
		this.startY = startY;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 23)
	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}

	public String getTextEn()
	{
		return this.textEn;
	}

	public void setTextEn(String textEn)
	{
		this.textEn = textEn;
	}

	public String getTextGm()
	{
		return this.textGm;
	}

	public void setTextGm(String textGm)
	{
		this.textGm = textGm;
	}

}
