package com.cj.security.entity;

// Generated 2012-12-28 14:40:32 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name = "sys_menu", catalog = "mysecurity")
public class SysMenu implements java.io.Serializable
{
	private static final long serialVersionUID = 4895093273403040859L;
	private Integer id;
	private String name;
	private String url;
	private String target;
	private Integer parent;
	private Boolean enable;
	private List<SysRole> sysRoles= new ArrayList<SysRole>();

	public SysMenu()
	{
	}

	public SysMenu(String name, String url, String target, Integer parent,
			Boolean enable, List<SysRole> sysRoles)
	{
		this.name = name;
		this.url = url;
		this.target = target;
		this.parent = parent;
		this.enable = enable;
		this.sysRoles = sysRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "url")
	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	@Column(name = "target", length = 50)
	public String getTarget()
	{
		return this.target;
	}

	public void setTarget(String target)
	{
		this.target = target;
	}

	@Column(name = "parent")
	public Integer getParent()
	{
		return this.parent;
	}

	public void setParent(Integer parent)
	{
		this.parent = parent;
	}

	@Column(name = "enable")
	public Boolean getEnable()
	{
		return this.enable;
	}

	public void setEnable(Boolean enable)
	{
		this.enable = enable;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "sysMenus")
	public List<SysRole> getSysRoles()
	{
		return this.sysRoles;
	}

	public void setSysRoles(List<SysRole> sysRoles)
	{
		this.sysRoles = sysRoles;
	}

}
