package com.cj.security.entity;

// Generated 2012-12-17 15:20:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysRoleResource generated by hbm2java
 */
@Entity
@Table(name = "sys_role_resource", catalog = "mysecurity")
public class SysRoleResource implements java.io.Serializable
{
	private static final long serialVersionUID = -4181275236273756245L;
	private Integer id;
	private SysRole sysRole;
	private SysResource sysResource;

	public SysRoleResource()
	{
	}

	public SysRoleResource(SysRole sysRole, SysResource sysResource)
	{
		this.sysRole = sysRole;
		this.sysResource = sysResource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "role_id")
	public SysRole getSysRole()
	{
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole)
	{
		this.sysRole = sysRole;
	}

	@ManyToOne
	@JoinColumn(name = "resource_id")
	public SysResource getSysResource()
	{
		return this.sysResource;
	}

	public void setSysResource(SysResource sysResource)
	{
		this.sysResource = sysResource;
	}

}
