package com.cj.security.entity;

// Generated 2012-12-28 14:40:32 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysRoleMenu generated by hbm2java
 */
@Entity
@Table(name = "sys_role_menu", catalog = "mysecurity")
public class SysRoleMenu implements java.io.Serializable
{
	private static final long serialVersionUID = 2962360392166642471L;
	private Integer id;
	private SysMenu sysMenu;
	private SysRole sysRole;

	public SysRoleMenu()
	{
	}

	public SysRoleMenu(SysMenu sysMenu, SysRole sysRole)
	{
		this.sysMenu = sysMenu;
		this.sysRole = sysRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id")
	public SysMenu getSysMenu()
	{
		return this.sysMenu;
	}

	public void setSysMenu(SysMenu sysMenu)
	{
		this.sysMenu = sysMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public SysRole getSysRole()
	{
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole)
	{
		this.sysRole = sysRole;
	}

}
