package com.cj.security.entity;

// Generated 2012-12-17 15:20:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", 
uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SysRole implements java.io.Serializable
{
	private static final long serialVersionUID = 2994365271202182530L;
	private Integer id;
	private String name;
	private Boolean enable;
	
	private List<SysUser> sysUsers=new ArrayList<SysUser>();
	private List<SysResource> sysResources=new ArrayList<SysResource>();
	private List<SysMenu> sysMenus=new ArrayList<SysMenu>();

	public SysRole()
	{
	}

	public SysRole(String name)
	{
		this.name = name;
	}

	public SysRole(String name, Boolean enable,
			List<SysUser> sysUsers,List<SysResource> sysResources,
			List<SysMenu> sysMenus)
	{
		this.name = name;
		this.enable = enable;
		this.sysUsers = sysUsers;
		this.sysResources = sysResources;
		this.sysMenus=sysMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "enable")
	public Boolean getEnable()
	{
		return this.enable;
	}

	public void setEnable(Boolean enable)
	{
		this.enable = enable;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "sysRoles")
	public List<SysUser> getSysUsers()
	{
		return this.sysUsers;
	}
	public void setSysUsers(List<SysUser> sysUsers)
	{
		this.sysUsers = sysUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name="sys_role_resource",
	joinColumns={@JoinColumn(name="role_id")},
	inverseJoinColumns={@JoinColumn(name="resource_id")})
	public List<SysResource> getSysResources()
	{
		return this.sysResources;
	}
	public void setSysResources(List<SysResource> sysResources)
	{
		this.sysResources = sysResources;
	}

	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name="sys_role_menu",
	joinColumns={@JoinColumn(name="role_id")},
	inverseJoinColumns={@JoinColumn(name="menu_id")})
	public List<SysMenu> getSysMenus()
	{ 
		return sysMenus;
	}

	public void setSysMenus(List<SysMenu> sysMenus)
	{
		this.sysMenus = sysMenus;
	}

}
