package com.cj.security.entity;

// Generated 2012-12-17 15:20:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user", 
uniqueConstraints = @UniqueConstraint(columnNames = "account"))
public class SysUser implements java.io.Serializable
{
	private static final long serialVersionUID = -4495420767035027632L;
	private Integer id;
	private String account;
	private String password;
	private Boolean enable;
	private List<SysRole> sysRoles=new ArrayList<SysRole>();

	public SysUser()
	{
	}

	public SysUser(String account)
	{
		this.account = account;
	}

	public SysUser(String account, String password, Boolean enable,
			List<SysRole> sysRoles)
	{
		this.account = account;
		this.password = password;
		this.enable = enable;
		this.sysRoles = sysRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "account", unique = true, nullable = false, length = 50)
	public String getAccount()
	{
		return this.account;
	}

	public void setAccount(String account)
	{
		this.account = account;
	}

	@Column(name = "password", length = 32)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Column(name = "enable")
	public Boolean getEnable()
	{
		return this.enable;
	}

	public void setEnable(Boolean enable)
	{
		this.enable = enable;
	}

	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name="sys_user_role",
	joinColumns={@JoinColumn(name="user_id")},
	inverseJoinColumns={@JoinColumn(name="role_id")})
	public List<SysRole> getSysRoles()
	{
		return this.sysRoles;
	}
	public void setSysRoles(List<SysRole> sysRoles)
	{
		this.sysRoles = sysRoles;
	}
}
