package com.cj.security.entity;

// Generated 2012-12-17 15:20:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysUserRole generated by hbm2java
 */
@Entity
@Table(name = "sys_user_role", catalog = "mysecurity")
public class SysUserRole implements java.io.Serializable
{
	private static final long serialVersionUID = -4945811441790694503L;
	private Integer id;
	private SysUser sysUser;
	private SysRole sysRole;

	public SysUserRole()
	{
	}

	public SysUserRole(SysUser sysUser, SysRole sysRole)
	{
		this.sysUser = sysUser;
		this.sysRole = sysRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public SysUser getSysUser()
	{
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser)
	{
		this.sysUser = sysUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public SysRole getSysRole()
	{
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole)
	{
		this.sysRole = sysRole;
	}

}
