package com.cj.ebike.entity;

// Generated 2012-12-4 14:02:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
public class Product implements java.io.Serializable
{

	private static final long serialVersionUID = 1L;
	private int id;
	private String productNameEn;
	private String productNameGm;
	private Integer parentId;
	private Integer isShow;
	private String imageUrl;
	private String descEn;
	private String descGm;
	private Date createDate;
	private Set<ProductDetailsByProperty> productDetailsByProperties = new HashSet<ProductDetailsByProperty>(
			0);
	private Set<ProductDetailsByImage> productDetailsByImages = new HashSet<ProductDetailsByImage>(
			0);

	public Product()
	{
	}

	public Product(int id)
	{
		this.id = id;
	}

	public Product(int id, String productNameEn, String productNameGm,
			Integer parentId, Integer isShow, String imageUrl, String descEn,
			String descGm, Date createDate,
			Set<ProductDetailsByProperty> productDetailsByProperties,
			Set<ProductDetailsByImage> productDetailsByImages)
	{
		this.id = id;
		this.productNameEn = productNameEn;
		this.productNameGm = productNameGm;
		this.parentId = parentId;
		this.isShow = isShow;
		this.imageUrl = imageUrl;
		this.descEn = descEn;
		this.descGm = descGm;
		this.createDate = createDate;
		this.productDetailsByProperties = productDetailsByProperties;
		this.productDetailsByImages = productDetailsByImages;
	}

	@Id
	@GeneratedValue
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getProductNameEn()
	{
		return this.productNameEn;
	}

	public void setProductNameEn(String productNameEn)
	{
		this.productNameEn = productNameEn;
	}

	public String getProductNameGm()
	{
		return this.productNameGm;
	}

	public void setProductNameGm(String productNameGm)
	{
		this.productNameGm = productNameGm;
	}

	public Integer getParentId()
	{
		return this.parentId;
	}

	public void setParentId(Integer parentId)
	{
		this.parentId = parentId;
	}

	public Integer getIsShow()
	{
		return this.isShow;
	}

	public void setIsShow(Integer isShow)
	{
		this.isShow = isShow;
	}

	public String getImageUrl()
	{
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl)
	{
		this.imageUrl = imageUrl;
	}

	public String getDescEn()
	{
		return this.descEn;
	}

	public void setDescEn(String descEn)
	{
		this.descEn = descEn;
	}

	public String getDescGm()
	{
		return this.descGm;
	}

	public void setDescGm(String descGm)
	{
		this.descGm = descGm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 23)
	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductDetailsByProperty> getProductDetailsByProperties()
	{
		return this.productDetailsByProperties;
	}

	public void setProductDetailsByProperties(
			Set<ProductDetailsByProperty> productDetailsByProperties)
	{
		this.productDetailsByProperties = productDetailsByProperties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductDetailsByImage> getProductDetailsByImages()
	{
		return this.productDetailsByImages;
	}

	public void setProductDetailsByImages(
			Set<ProductDetailsByImage> productDetailsByImages)
	{
		this.productDetailsByImages = productDetailsByImages;
	}

}
